lab9/src/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy

from .views import RegisterView

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {"next_page" : reverse_lazy('accounts:login')}, name='logout'),
    url('^register/', RegisterView.as_view(), name='register'),
]

lab9/src/config/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('notes/')),
    url(r'^admin/', admin.site.urls),
    # apps
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^notes/', include('notes.urls', namespace="notes")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab9/src/notes/urls.py
from django.conf.urls import url
from .views import NoteList, NoteDetail, NoteCreate, NoteUpdate, NoteDelete

from . import views

urlpatterns = [
    url(r'^$', NoteList.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', NoteDetail.as_view(), name='detail'),
    url(r'^new/$', NoteCreate.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/edit/$', NoteUpdate.as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', NoteDelete.as_view(), name='delete'),
]

lab9/src/accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

lab9/src/django_wysiwyg/models.py
# only for unittest

lab9/src/notes/models.py
from django.db import models
from datetime import timedelta
from django.utils import timezone
from django.contrib.auth.models import User

class Note(models.Model):
    title = models.CharField(max_length=200)
    tags = models.CharField(max_length=100)
    body = models.TextField()
    pub_date = models.DateTimeField('date published')
    owner = models.ForeignKey(User, related_name='notes', on_delete=models.CASCADE, default=1)

    def was_published_recently(self):
        now = timezone.now()
        return now - timedelta(days=1) <= self.pub_date <= now

lab9/src/notes/forms.py
from django import forms

from .models import Note

class NoteForm(forms.ModelForm):

    class Meta:
        model = Note
        exclude = ['owner', 'pub_date']

lab9/src/accounts/views.py
from __future__ import unicode_literals
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import FormView


class RegisterView(FormView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url='/'

    def form_valid(self, form):
        # save the new user first
        form.save()

        # get the username and password
        username = self.request.POST['username']
        password = self.request.POST['password1']

        # authenticate user then login
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return super(RegisterView, self).form_valid(form)

lab9/src/notes/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.utils import timezone
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector

from .models import Note
from .forms import NoteForm
from .mixins import NoteMixin

import re

@login_required
def index(request):
    # latest_note_list = Note.objects.order_by('-pub_date')[:5]
    latest_note_list = Note.objects.filter(owner=request.user).order_by('-pub_date')
    context = {
        'latest_note_list': latest_note_list,
    }
    return render(request, 'notes/index.html', context)

@login_required
def detail(request, note_id):
     note = get_object_or_404(Note, pk=note_id)
     return render(request, 'notes/detail.html', {'note': note})

class NoteList(ListView):
    paginate_by = 5
    template_name = 'notes/index.html'
    context_object_name = 'latest_note_list'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(NoteList, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        notes = Note.objects.filter(owner=self.request.user).order_by('-pub_date')
        search_query = self.request.GET.get('q')
        if search_query:
            if 'tag:' in search_query:
                # search by tag
                tag = search_query.replace('tag:', '')
                notes = list(filter(lambda item: tag in item.tags.split(","), notes))
            else:
                # search by title and body content
                notes = list(filter(lambda item: search_query in item.title or search_query in item.body, notes))
        return notes


class NoteDetail(DetailView):
    model = Note
    template_name = 'notes/detail.html'
    context_object_name = 'note'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(NoteDetail, self).dispatch(*args, **kwargs)

class NoteCreate(LoginRequiredMixin, NoteMixin, CreateView):
    form_class = NoteForm
    template_name = 'notes/form.html'
    success_url = reverse_lazy('notes:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.pub_date = timezone.now()
        return super(NoteCreate, self).form_valid(form)

class NoteUpdate(LoginRequiredMixin, NoteMixin, UpdateView):
    model = Note
    form_class = NoteForm
    template_name = 'notes/form.html'
    success_url = reverse_lazy('notes:index')

    def form_valid(self, form):
       form.instance.pub_date = timezone.now()
       return super(NoteUpdate, self).form_valid(form)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.owner != self.request.user:
            raise PermissionDenied

        return super(NoteUpdate, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.owner != self.request.user:
            raise PermissionDenied

        return super(NoteUpdate, self).post(request, *args, **kwargs)

class NoteDelete(LoginRequiredMixin, NoteMixin, DeleteView):
    model = Note
    success_url = reverse_lazy('notes:index')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.check_user_or_403(self.object.owner)
        return super(NoteDelete, self).post(request, *args, **kwargs)

def get(self, request, *args, **kwargs):
    self.object = self.get_object()

    if self.object.owner != self.request.user:
        raise PermissionDenied

    context = self.get_context_data(object=self.object)
    return self.render_to_response(context)

def get_success_url(self):
    return reverse('notes:update', kwargs={
        'pk': self.object.pk
    })

lab9/src/django-ckeditor/templates/ckeditor/widget.html
{% load static %}
<div class="django-ckeditor-widget" data-field-id="{{id}}" style="display: inline-block;">
    <textarea{{ final_attrs }} data-processed="0" data-config="{{ config }}" data-external-plugin-resources="{{ external_plugin_resources }}" data-id="{{id}}" data-type="ckeditortype">{{ value }}</textarea>
</div>

lab9/src/django_wysiwyg/templates/django_wysiwyg/alloyeditor/editor_instance.html
{% comment %}
    We're deliberately injecting our editor into the global namespace so it
    can be manipulated by user JavaScript.
{% endcomment %}

<script type="text/javascript">
    (function(){
	    var config = {{ config|default:"null" }};

        django_wysiwyg.enable('{{ editor_name }}', '{{ field_id }}', config);
    })();
</script>

lab9/src/django_wysiwyg/templates/django_wysiwyg/alloyeditor/includes.html
{% comment %}
    Alloy Editor requires you to have the resources referenced below installed under your STATIC_URL/alloyeditor.
    You can download them from alloyeditor.com
{% endcomment %}
{% load wysiwyg %}

<link href="{% wysiwyg_static_url 'alloyeditor' 'alloyeditor/' DJANGO_WYSIWYG_MEDIA_URL %}assets/alloy-editor-ocean-min.css" rel="stylesheet">
<script type="text/javascript" src="{% wysiwyg_static_url 'alloyeditor' 'alloyeditor/' DJANGO_WYSIWYG_MEDIA_URL %}alloy-editor-all-min.js"></script>
<script type="text/javascript">
    // allow custom settings per editor ID:
    var django_wysiwyg_editor_configs = [];{% block django_wysiwyg_editor_config %}
    var django_wysiwyg_editor_config = {};
  {% endblock %}

  var django_wysiwyg =
    {
        editors: {},

        enable: function django_wysiwyg_enable(editor_name, field_id, config)
        {
            if( !config ) {
                config = django_wysiwyg_editor_configs[field_id] || django_wysiwyg_editor_config;
            }

            if( !this.editors[editor_name] ) {
                this.editors[editor_name] = AlloyEditor.editable(field_id, config);
            }
        },

        disable: function django_wysiwyg_disable(editor_name)
        {
            var editor = this.editors[editor_name];
            if( editor ) {
                editor.destroy(/*noUpdate=*/false);
                this.editors[editor_name] = null;
            }
        },

        is_loaded: function django_wysiwyg_is_loaded()
        {
            return window.AlloyEditor != null;
        }
    }
</script>

lab9/src/django_wysiwyg/templates/django_wysiwyg/ckeditor/editor_instance.html
{% comment %}
    We're deliberately injecting our editor into the global namespace so it
    can be manipulated by user JavaScript.
{% endcomment %}

<script type="text/javascript">
    (function(){
	    var config = {{ config|default:"null" }};

        django_wysiwyg.enable('{{ editor_name }}', '{{ field_id }}', config);
    })();
</script>

lab9/src/django_wysiwyg/templates/django_wysiwyg/ckeditor/includes.html
{% comment %}
    CKEditor requires you to have the resources referenced below installed under your STATIC_URL/ckeditor.
    You can download them from ckeditor.com, or include django-ckeditor in your project.
{% endcomment %}
{% load wysiwyg %}
<script type="text/javascript" src="{% wysiwyg_static_url 'ckeditor' 'ckeditor/ckeditor/' DJANGO_WYSIWYG_MEDIA_URL %}ckeditor.js"></script>
<script type="text/javascript">
    // allow custom settings per editor ID:
    var django_wysiwyg_editor_configs = [];{% block django_wysiwyg_editor_config %}
    var django_wysiwyg_editor_config = {};
  {% endblock %}

  var django_wysiwyg =
    {
        editors: {},

        enable: function django_wysiwyg_enable(editor_name, field_id, config)
        {
            if( !config ) {
                config = django_wysiwyg_editor_configs[field_id] || django_wysiwyg_editor_config;
            }

            if( !this.editors[editor_name] ) {
                this.editors[editor_name] = CKEDITOR.replace(field_id, config);
            }
        },

        disable: function django_wysiwyg_disable(editor_name)
        {
            var editor = this.editors[editor_name];
            if( editor ) {
                editor.destroy(/*noUpdate=*/false);
                this.editors[editor_name] = null;
            }
        },

        is_loaded: function django_wysiwyg_is_loaded()
        {
            return window.CKEDITOR != null;
        }
    }
</script>

lab9/src/django_wysiwyg/templates/django_wysiwyg/froala/editor_instance.html
<script type="text/javascript">
    (function() {
        var config = {{ config|default:"null" }};

        django_wysiwyg.enable('{{ editor_name }}', '{{ field_id }}', config);
    })();
</script>

lab9/src/django_wysiwyg/templates/django_wysiwyg/froala/includes.html
{% comment %}
    froala requires you to have the resources referenced below installed under your STATIC_URL.
    You can download them from http://editor.froala.com/download
{% endcomment %}

{% load wysiwyg %}
<!-- jquery is required for froala -->
<script src="http://code.jquery.com/jquery-1.10.2.js"></script>

<link rel="stylesheet" type="text/css" href="{{ DJANGO_WYSIWYG_MEDIA_URL }}css/font-awesome.min.css"/>
<link rel="stylesheet" type="text/css" href="{{ DJANGO_WYSIWYG_MEDIA_URL }}css/froala_editor.min.css"/>
<script type="text/javascript" src="{{ DJANGO_WYSIWYG_MEDIA_URL }}froala_editor.min.js"></script>

<script type="text/javascript">
    // allow custom settings per editor ID:
    var django_wysiwyg_editor_configs = [];{% block django_wysiwyg_editor_config %}
    var django_wysiwyg_editor_config = {};
{% endblock %}

    var django_wysiwyg =
    {
        editors: {},

        enable: function django_wysiwyg_enable(editor_name, field_id, config)
        {
            if( !config ) {
                config = django_wysiwyg_editor_configs[field_id] || django_wysiwyg_editor_config;
            }

            if( !this.editors[editor_name] ) {
                jQuery.fn.ready(function(){
                    django_wysiwyg.editors[editor_name] = jQuery("#" + field_id).editable(config);
                });
            }
        },

        disable: function django_wysiwyg_disable(editor_name)
        {
            var editor = this.editors[editor_name];
            if( editor ) {
                editor.destroyEditor();
                this.editors[editor_name] = null;
            }
        },

        is_loaded: function django_wysiwyg_is_loaded()
        {
            return window.jQuery != null && window.jQuery.fn.editable != null;
        }
    }
</script>

lab9/src/django_wysiwyg/templates/django_wysiwyg/redactor/editor_instance.html
<script type="text/javascript">
    (function() {
        var config = {{ config|default:"null" }};

        django_wysiwyg.enable('{{ editor_name }}', '{{ field_id }}', config);
    })();
</script>

lab9/src/django_wysiwyg/templates/django_wysiwyg/redactor/includes.html
{% comment %}
    Refactor requires you to have the resources referenced below installed under your STATIC_URL.
    You can download them from http://redactorjs.com/
{% endcomment %}

{% load wysiwyg %}
<link rel="stylesheet" type="text/css" href="{{ DJANGO_WYSIWYG_MEDIA_URL }}css/redactor.css"/>
<script type="text/javascript" src="{{ DJANGO_WYSIWYG_MEDIA_URL }}redactor.min.js"></script>
<script type="text/javascript">
    // allow custom settings per editor ID:
    var django_wysiwyg_editor_configs = [];{% block django_wysiwyg_editor_config %}
    var django_wysiwyg_editor_config = {};
{% endblock %}

    var django_wysiwyg =
    {
        editors: {},

        enable: function django_wysiwyg_enable(editor_name, field_id, config)
        {
            if( !config ) {
                config = django_wysiwyg_editor_configs[field_id] || django_wysiwyg_editor_config;
            }

            if( !this.editors[editor_name] ) {
                jQuery.fn.ready(function(){
                    django_wysiwyg.editors[editor_name] = jQuery("#" + field_id).redactor(config);
                });
            }
        },

        disable: function django_wysiwyg_disable(editor_name)
        {
            var editor = this.editors[editor_name];
            if( editor ) {
                editor.redactor('core.destroy');
                this.editors[editor_name] = null;
            }
        },

        is_loaded: function django_wysiwyg_is_loaded()
        {
            return window.jQuery != null && window.jQuery.fn.redactor != null;
        }
    }
</script>

lab9/src/django_wysiwyg/templates/django_wysiwyg/tinymce/editor_instance.html
<script type="text/javascript">
    (function() {
        var config = {{ config|default:"null" }};

        django_wysiwyg.enable('{{ editor_name }}', '{{ field_id }}', config);
    })();
</script>

lab9/src/django_wysiwyg/templates/django_wysiwyg/tinymce/includes.html
{% comment %}
    TinyMCE requires you to have the resources referenced below installed under your STATIC_URL/tinymce.
    You can download them from tinymce.com, or include django-tinymce in your project.
{% endcomment %}
{% load wysiwyg %}
<script type="text/javascript" src="{% wysiwyg_static_url 'tinymce' 'tiny_mce/' DJANGO_WYSIWYG_MEDIA_URL %}tiny_mce_src.js"></script>
<script type="text/javascript">
    // allow custom settings per editor ID:
    var django_wysiwyg_editor_configs = [];{% block django_wysiwyg_editor_config %}
    var django_wysiwyg_editor_config = {
        relative_urls: false,
        custom_undo_redo_levels: 10,
        plugins: 'paste,autoresize',
        strict_loading_mode: true,  // for pre 3.4 releases

        width: '610px',
        theme: "simple"
    };
{% endblock %}

    var django_wysiwyg =
    {
        editors: {},

        enable: function django_wysiwyg_enable(editor_name, field_id, config)
        {
            if( !this.editors[editor_name] ) {
                if( !config ) {
                    config = django_wysiwyg_editor_configs[field_id] || django_wysiwyg_editor_config;
                }

                // Apply extra settings in local copy.
                var localconfig = {};
                tinyMCE.extend(localconfig, config);
                tinyMCE.extend(localconfig, {
                    mode: "exact",
                    elements: field_id,
                    setup: function(editor) {
                        django_wysiwyg.editors[editor_name] = editor;
                    }
                });

                tinyMCE.init(localconfig);
            }
        },

        disable: function django_wysiwyg_disable(editor_name)
        {
            var editor = this.editors[editor_name];
            if( editor ) {
                editor.save();
                editor.remove();
                this.editors[editor_name] = null;
            }
        },

        is_loaded: function django_wysiwyg_is_loaded()
        {
            return window.tinyMCE != null;
        }
    }
</script>

lab9/src/django_wysiwyg/templates/django_wysiwyg/yui/editor_instance.html
{% comment %}
    We're deliberately injecting our editor into the global namespace so it
    can be manipulated by user JavaScript.
{% endcomment %}

<script type="text/javascript">
    YAHOO.util.Event.onAvailable("{{ field_id }}", function() {
        django_wysiwyg.enable('{{ editor_name }}', '{{ field_id }}');
    });
</script>

lab9/src/django_wysiwyg/templates/django_wysiwyg/yui/includes.html
{% load i18n %}
{% comment %}
    This is hosted using the Yahoo CDN. You can override this if you prefer to host locally.

    To include other parts of YUI, visit the configurator here:

    http://developer.yahoo.com/yui/articles/hosting/?editor&MIN
{% endcomment %}


{% comment %}
    TODO: YUI values should be superseded by DJANGO_WYSWYG_MEDIA_URL - should we just hardcode the name combo.js / combo.css or do something more configurable?
{% endcomment %}

<!-- Combo-handled YUI CSS files: -->
<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/combo?2.9.0/build/assets/skins/sam/skin.css">
<!-- Combo-handled YUI JS files: -->
<script type="text/javascript" src="http://yui.yahooapis.com/combo?2.9.0/build/yahoo-dom-event/yahoo-dom-event.js&amp;2.9.0/build/container/container_core-min.js&amp;2.9.0/build/menu/menu-min.js&amp;2.9.0/build/element/element-min.js&amp;2.9.0/build/button/button-min.js&amp;2.9.0/build/editor/editor-min.js"></script>

<script type="text/javascript" charset="utf-8">
    "use strict";

    // This is required for Yahoo's skins:
    if( window.YAHOO ) {
        YAHOO.util.Event.onDOMReady(function() { YAHOO.util.Dom.addClass(document.body, 'yui-skin-sam'); });
    }


    /*
        This config is used for our standard rich editor on the site and in the
        Django admin area if you've modified the change_form.html to enable
        rich editing.

        See Yahoo's documentation for customization options:

        http://developer.yahoo.com/yui/editor/
    */

    var django_wysiwyg_editor_configs = [];   // allow custom settings per editor ID
{% block django_wysiwyg_editor_config %}
    var django_wysiwyg_editor_config = {
        height: "400px",
        width: "624px",
        animate: true,
        autoHeight: true,
        // BUG: handleSubmit breaks contrib.admin's save-and-continue-editing feature - we can avoid by listening for blur events
        // This will cause the rich editor to update the original textarea's value when the containing form submit event fires
        handleSubmit: true,
        focusAtStart: false,
        toolbar: {
            //collapse: true,
            //titlebar: 'Body',
            draggable: false,
            buttons: [
            {
                group: 'fontstyle',
                label: '{% trans "Font Name and Size" %}',
                buttons: [
                    { type: 'select', label: 'Arial', value: 'fontname', disabled: true,
                      menu: [
                        { text: 'Arial', checked: true },
                        { text: 'Arial Black' },
                        { text: 'Comic Sans MS' },
                        { text: 'Courier New' },
                        { text: 'Georgia' },
                        { text: 'Impact' },
                        { text: 'Lucida Console' },
                        { text: 'Tahoma' },
                        { text: 'Times New Roman' },
                        { text: 'Trebuchet MS' },
                        { text: 'Verdana' }
                      ]
                    },
                    { type: 'spin', label: '13', value: 'fontsize', range: [9, 75], disabled: true }
                ]
            },
            {
                type: 'separator'
            },
            {
                group: 'textstyle',
                label: '{% trans "Font Style" %}',
                buttons: [
                    { type: 'push', label: '{% trans "Bold CTRL + SHIFT + B" %}', value: 'bold' },
                    { type: 'push', label: '{% trans "Italic CTRL + SHIFT + I" %}', value: 'italic' },
                    { type: 'push', label: '{% trans "Underline CTRL + SHIFT + U" %}', value: 'underline' },
                    { type: 'separator' },
                    { type: 'color', label: '{% trans "Font Color" %}', value: 'forecolor', disabled: true },
                    { type: 'color', label: '{% trans "Background Color" %}', value: 'backcolor', disabled: true }
                ]
            },
            {
                type: 'separator'
            },
            {
                group: 'indentlist',
                label: '{% trans "Lists" %}',
                buttons: [
                    { type: 'push', label: '{% trans "Create an Unordered List" %}', value: 'insertunorderedlist' },
                    { type: 'push', label: '{% trans "Create an Ordered List" %}', value: 'insertorderedlist' }
                ]
            },
            {
                type: 'separator'
            },
            {
                group: 'insertitem',
                label: '{% trans "Insert Item" %}',
                buttons: [
                    { type: 'push', label: '{% trans "HTML Link CTRL + SHIFT + L" %}', value: 'createlink', disabled: true },
                    { type: 'push', label: '{% trans "Insert Image" %}', value: 'insertimage' }
                ]
            }
            ]
        }
    };
{% endblock %}

    var django_wysiwyg =
    {
        editors: {},

        enable: function django_wysiwyg_enable(editor_name, field_id, config)
        {
            if( !config ) {
                config = django_wysiwyg_editor_configs[field_id] || django_wysiwyg_editor_config;
            }
            if( !this.editors[editor_name] ) {
              this.editors[editor_name] = new YAHOO.widget.Editor(field_id, config);
              this.editors[editor_name].render();
            }
        },

        disable: function django_wysiwyg_disable(editor_name)
        {
            var editor = this.editors[editor_name];
            if( editor ) {
                editor.saveHTML();
                editor.destroy();
                this.editors[editor_name] = null;
            }
        },

        is_loaded: function django_wysiwyg_is_loaded()
        {
          return window.YAHOO != null
              && window.YAHOO.widget != null
              && window.YAHOO.widget.Editor != null;
        }
    }
</script>

lab9/src/templates/notes/form.html
{% extends "base.html" %}

{% block content %}

{% load wysiwyg %}
{% wysiwyg_setup %}


    <div class="row">
        {% if notes %}
        <div class="col-xs-4">
            <nav id="sidebar">

              {% if notes %}
              <div class="new-note">
                <a href="{% url 'notes:create' %}" class="new-note btn btn-default">+ New Note</a>
              </div>
              {% endif %}

              <ul id="notes">

                  {% for note in notes %}
                    <li data-url="{% url 'notes:update' note.id %}"
                    {% if object and object.pk == note.pk %}
                    style="color: white; background-color: #2dbe60;"
                    {% endif %}
                    >
                        <div class="note-title"
                        {% if object and object.pk == note.pk %}
                        style="color: white"
                        {% endif %}
                        >{{ note.title }}</div>
                        <div class="note-body">{{ note.body|truncatechars:100 | safe }}</div>
                    </li>
                  {% endfor %}
              </ul>
            </nav>
        </div>
        {% endif %}

        <div class="col-xs-8">

        {% if form.errors %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}

        {% if object %}
        <form id="note_content" action="{% url 'notes:update' object.pk %}" method="post" accept-charset="utf-8">
        {% else %}
        <form id="note_content" action="{% url 'notes:create' %}" method="post" accept-charset="utf-8">
        {% endif %}

            {% csrf_token %}
            {% for field in form %}
            <p>
                {% if field.errors %}
            	<div class="alert alert-danger" role="alert">
                    {{ field.errors }}
            	</div>
                {% endif %}
                {{ field }}
            </p>
            {% endfor %}
            <input type="hidden" name="next" value="{{ next }}" />

        {% if object %}
            <input class="btn btn-default" type="button" id="btn_UpdateNote" value="Update Note"/>
        {% else %}
            <input class="btn btn-default" type="submit" value="Create Note"/>
        {% endif %}
        </form>

        {% if object %}
        <form action="{% url 'notes:delete' object.pk %}" method="post" id="delete-note-form">
          {% csrf_token %}
          <a class="btn btn-default" id="delete-note">
            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
          </a>
        </form>
        {% endif %}

        <div id="message_block" style="display: none; width: 25%"></div>

        </div>
    </div>

{% wysiwyg_editor "id_body" %}

{% endblock %}

lab9/src/templates/notes/index.html
{% extends "base.html" %}

{% block content %}

{% if keywords %}
ololo
{% endif %}

{% if latest_note_list %}
<div class="leftmarginblock" style="font-size: 115%">
  <h4 style="color: black">Notes</h4><br>
  <form action="" method="get" accept-charset="utf-8">
      <input class="searchfield" name="q" type="text" placeholder="Text to search (tag:value)" value="{{ request.GET.q }}">
      <input type="submit" value="Search" />
  </form>
  {% for note in latest_note_list %}
  <li>
    <a href="{% url 'notes:detail' note.id %}">{{ note.title }}</a>
    <a href="{% url 'notes:update' note.id %}">(Edit)</a>
    <hr>
  </li>
  {% endfor %}
</div>
{% else %}
<div class="leftmarginblock">
  {% if request.GET.q %}
  <p>Nothing found. <a href="/">Back to notes list</a></p>
  {% else %}
  <p>No notes available. </p>
  But you can create <a href="{% url 'notes:create' %}">a new one</a>
  {% endif %}
</div>
{% endif %}

{% if is_paginated %}
<div class="pagination">
   <span class="step-links">
       {% if page_obj.has_previous %}
           <a href="?page={{ page_obj.previous_page_number }}">previous</a>
       {% endif %}

       <span class="current">
           Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
       </span>

       {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
       {% endif %}
  </span>
</div>
{% endif %}

{% endblock %}